version: '3'

networks:
  redis-cluster:
    driver: bridge

# 定义公共参数
x-redis-common: &redis-common
  image: redis:7
  networks:
    - redis-cluster
  deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 64M

services:
  redis1:
    container_name: redis-1
    ports:
      - "7001:6379"
      - "17001:16379"
    volumes:
      - ./redis-data/7001:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-1", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7001
      --cluster-announce-bus-port 17001
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  redis2:
    container_name: redis-2
    ports:
      - "7002:6379"
      - "17002:16379"
    volumes: 
      - ./redis-data/7002:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-2", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    depends_on:
      - redis1
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7002
      --cluster-announce-bus-port 17002
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  redis3:
    container_name: redis-3
    ports:
      - "7003:6379"
      - "17003:16379"
    volumes: 
      - ./redis-data/7003:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-3", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    depends_on:
      - redis1
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7003
      --cluster-announce-bus-port 17003
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  redis4:
    container_name: redis-4
    ports:
      - "7004:6379"
      - "17004:16379"
    volumes: 
      - ./redis-data/7004:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-4", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    depends_on:
      - redis1
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7004
      --cluster-announce-bus-port 17004
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  redis5:
    container_name: redis-5
    ports:
      - "7005:6379"
      - "17005:16379"
    volumes:
      - ./redis-data/7005:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-5", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    depends_on:
      - redis1
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7005
      --cluster-announce-bus-port 17005
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  redis6:
    container_name: redis-6
    ports:
      - "7006:6379"
      - "17006:16379"
    volumes:
      - ./redis-data/7006:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "redis-6", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
    depends_on:
      - redis1
    command: >
      redis-server
      --cluster-enabled yes
      --cluster-config-file nodes.conf
      --cluster-node-timeout 5000
      --cluster-announce-ip ${IPV4}
      --cluster-announce-port 7006
      --cluster-announce-bus-port 17006
      --cluster-replica-no-failover yes
      --appendonly yes
      --save 300 1000
      --save 60 10000
      --requirepass ${REDIS_PASSWORD}
      --masterauth ${REDIS_PASSWORD}
      --maxmemory 64m
      --maxmemory-policy allkeys-lru
      --protected-mode no
      --bind 0.0.0.0
    <<: *redis-common

  create-cluster:
    container_name: create-redis-cluster
    image: redis:7
    command: bash -c "sleep 5 && redis-cli --cluster create redis1:6379 redis2:6379 redis3:6379 redis4:6379 redis5:6379 redis6:6379 --cluster-replicas 1 --cluster-yes -a ${REDIS_PASSWORD}"
    networks:
      - redis-cluster
    depends_on:
      redis1:
        condition: service_healthy
      redis2:
        condition: service_healthy
      redis3:
        condition: service_healthy
      redis4:
        condition: service_healthy
      redis5:
        condition: service_healthy
      redis6:
        condition: service_healthy
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}